version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 9090:80

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

#version: "3"
#services:
#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - /home/ubuntu/ssl:/etc/nginx/certs
#
#  backend:
#    restart: always
#    container_name: backend
#    build: ./backend
#    expose:
#      - 5000
#    volumes:
#      - ./backend:/usr/src/app
#    environment:
#      - FLASK_ENV=development
#      - FLASK_APP=app.py
      - FLASK_DEBUG=1