version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 9090:80

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

  mongodb:
    container_name: mongodb
    image: mongo:latest
    network_mode: host
    environment:
      - AUTH: yes
      - MONGO_INITDB_ROOT_USENAME: root
      - MONGO_INITDB_ROOT_PASSWORD: personalguide2020
      - MONGO_INITDB_DATABASE: database
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
