version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 9090:80

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
