Tags = {
    'amenity': {
        'bench': ['bench'],
        'atm': ['finance'],
        'bank': ['finance'],
        'bureau_de_change': ['finance'],
        'pub': ['food'],
        'bar': ['food'],
        'bbq': ['food'],
        'biergarten': ['food'],
        'cafe': ['food'],
        'fast_food': ['food'],
        'food_court': ['food'],
        'ice_cream': ['food'],
        'restaurant': ['food'],
        'pharmacy': ['pharmacy'],
        'post_box': ['post'],
        'post_depot': ['post'],
        'post_office': ['post'],
        'recycling': ['recycling'],
        'marketplace': ['shop'],
        'telephone': ['telephone'],
        'drinking_water': ['water'],
        'water_point': ['water'],
        'toilets': ['wc'],
        'arts_centre': ['entertainment'],
        'casino': ['entertainment'],
        'cinema': ['entertainment'],
        'gambling': ['entertainment'],
        'planetarium': ['entertainment'],
        'theatre': ['entertainment'],
        'place_of_worship': ['religion'],
        'fountain': ['tourism']},
    'artwork_type': {
        'architecture': ['architecture'],
        'sculpture': ['tourism'],
        'statue': ['tourism'],
        'mural': ['tourism'],
        'stone': ['tourism'],
        'painting': ['tourism']},
    'atm': {
        'yes': ['finance']},
    'bicycle': {
        'yes': ['bicycle']},
    'bicycle_road': {
        'yes': ['bicycle']},
    'building': {
        'cathedral': ['religion'],
        'chapel': ['religion'],
        'church': ['religion'],
        'mosque': ['religion'],
        'religious': ['religion'],
        'shrine': ['religion'],
        'synagogue': ['religion'],
        'temple': ['religion']},
    'building:architecture': {
        'romanesque': ['architecture'],
        'gothic': ['architecture'],
        'renaissance': ['architecture'],
        'mannerism': ['architecture'],
        'baroque': ['architecture'],
        'rococo': ['architecture'],
        'neoclassicism': ['architecture'],
        'empire': ['architecture'],
        'pseudo-russian': ['architecture'],
        'eclectic': ['architecture'],
        'neo-gothic': ['architecture'],
        'pseudo-gothic': ['architecture'],
        'russian_gothic': ['architecture'],
        'art_nouveau': ['architecture'],
        'modern': ['architecture'],
        'constructivism': ['architecture'],
        'stalinist_neoclassicism': ['architecture'],
        'postmodern': ['architecture'],
        'contemporary': ['architecture']},
    'embedded_rails': {
        'yes': ['dangerous']},
    'foot': {
        'yes': ['footway']},
    'footway': {
        'crossing': ['footway'],
        'sidewalk': ['footway']},
    'ford': {
        'yes': ['dangerous']},
    'highway': {
        'living_street': ['courtyard'],
        'service': ['courtyard'],
        'pedestrian': ['courtyard'],
        'footway': ['footway'],
        'path': ['footway'],
        'steps': ['steps'],
        'track': ['trail'],
        'cycleway': ['bicycle'],
        'motorway_link': ['link'],
        'trunk_link': ['link'],
        'primary_link': ['link'],
        'secondary_link': ['link'],
        'tertiary_link': ['link'],
        'motorway': ['road'],
        'trunk': ['road'],
        'primary': ['road'],
        'secondary': ['road'],
        'tertiary': ['road'],
        'unclassified': ['road'],
        'residential': ['road'],
        'escape': ['road'],
        'raceway': ['road'],
        'road': ['road']},
    'historic': {
        'aircraft': ['historic'],
        'aqueduct': ['historic'],
        'archaeological_site': ['historic'],
        'boundary_stone': ['historic'],
        'castle_wall': ['historic'],
        'city_gate': ['historic'],
        'citywalls': ['historic'],
        'fort': ['historic'],
        'gallows': ['historic'],
        'highwater_mark': ['historic'],
        'locomotive': ['historic'],
        'mine': ['historic'],
        'mine_shaft': ['historic'],
        'milestone': ['historic'],
        'optical_telegraph': ['historic'],
        'pillory': ['historic'],
        'railway_car': ['historic'],
        'ruins': ['historic'],
        'rune_stone': ['historic'],
        'tomb': ['historic'],
        'vehicle': ['historic'],
        'wreck': ['historic'],
        'yes': ['historic'],
        'user defined': ['historic'],
        'ship': ['historic'],
        'building': ['historic', 'architecture'],
        'farm': ['historic', 'architecture'],
        'manor': ['historic', 'architecture'],
        'tower': ['historic', 'architecture'],
        'battlefield': ['historic', 'military'],
        'cannon': ['historic', 'military'],
        'castle': ['historic', 'military'],
        'tree_shrine': ['religion', 'historic'],
        'wayside_cross': ['religion', 'historic'],
        'wayside_shrine': ['religion', 'historic'],
        'church': ['religion', 'historic', 'architecture'],
        'monastery': ['religion', 'historic', 'architecture'],
        'memorial': ['tourism'],
        'monument': ['tourism']},
    'hop': {
        'alcohol': ['shop']},
    'ice_road': {
        'yes': ['dangerous']},
    'lit': {
        'yes': ['road properties'],
        'no': ['road properties']},
    'living_street': {
        'yes': ['courtyard']},
    'natural': {
        'tree_row': ['natural'],
        'wood': ['natural'],
        'heath': ['natural']},
    'religion': {
        'buddhist': ['religion'],
        'christian': ['religion'],
        'hindu': ['religion'],
        'jain': ['religion'],
        'jewish': ['religion'],
        'muslim': ['religion'],
        'pagan': ['religion'],
        'shinto': ['religion'],
        'sikh': ['religion'],
        'taoist': ['religion'],
        'zoroastrian': ['religion']},
    'sac_scale': {
        'hiking': ['hiking'],
        'mountain_hiking': ['hiking'],
        'demanding_mountain_hiking': ['hiking'],
        'alpine_hiking': ['hiking'],
        'demanding_alpine_hiking': ['hiking'],
        'difficult_alpine_hiking': ['hiking']},
    'service': {
        'alley': ['road'],
        'driveway': ['road'],
        'parking_aisle': ['road']},
    'shop': {
        'supermarket': ['shop'],
        'bakery': ['shop'],
        'beverages': ['shop'],
        'brewing_supplies': ['shop'],
        'butcher': ['shop'],
        'cheese': ['shop'],
        'chocolate': ['shop'],
        'coffee': ['shop'],
        'confectionery': ['shop'],
        'convenience': ['shop'],
        'deli': ['shop'],
        'dairy': ['shop'],
        'farm': ['shop'],
        'frozen_food': ['shop'],
        'greengrocer': ['shop'],
        'health_food': ['shop'],
        'ice_cream': ['shop'],
        'organic': ['shop'],
        'pasta': ['shop'],
        'pastry': ['shop'],
        'seafood': ['shop'],
        'spices': ['shop'],
        'tea': ['shop'],
        'wine': ['shop'],
        'water': ['shop', 'water']},
    'sidewalk': {
        'both': ['footway'],
        'left': ['footway'],
        'right': ['footway'],
        'yes': ['footway']},
    'surface': {
        'paved': ['surface'],
        'asphalt': ['surface'],
        'concrete': ['surface'],
        'concrete:lanes': ['surface'],
        'concrete:plates': ['surface'],
        'paving_stones': ['surface'],
        'sett': ['surface'],
        'unhewn_cobblestone': ['surface'],
        'cobblestone': ['surface'],
        'cobblestone:flattened': ['surface'],
        'metal': ['surface'],
        'wood': ['surface'],
        'unpaved': ['surface'],
        'compacted': ['surface'],
        'fine_gravel': ['surface'],
        'gravel': ['surface'],
        'pebblestone': ['surface'],
        'ground': ['surface'],
        'dirt': ['surface'],
        'earth': ['surface'],
        'grass': ['surface'],
        'grass_paver': ['surface'],
        'mud': ['surface'],
        'sand': ['surface'],
        'woodchips': ['surface'],
        'snow': ['surface'],
        'ice': ['surface'],
        'salt': ['surface']},
    'tourism': {
        'aquarium': ['entertainment'],
        'artwork': ['entertainment'],
        'gallery': ['entertainment'],
        'museum': ['entertainment'],
        'theme_park': ['entertainment'],
        'zoo': ['entertainment'],
        'attraction': ['tourism'],
        'information': ['tourism'],
        'viewpoint': ['tourism'],
        'yes': ['tourism']}}

tags_filter = [['tourism', 'artwork']] + [['amenity', 'atm'], ['atm', 'yes']] + [['amenity', 'bank']] + [
    ['amenity', 'bureau_de_change']] + [['amenity', 'cafe']] + [['amenity', 'cinema']] + [['amenity', 'fast_food']] + [
           ['amenity', 'fountain']] + [['amenity', 'pharmacy']] + [['amenity', 'place_of_worship'],
                                                                   ['building', 'religious'],
                                                                   ['historic', 'wayside_shrine'],
                                                                   ['historic', 'wayside_cross']] + [
           ['amenity', 'planetarium']] + [['amenity', 'post_box']] + [['amenity', 'post_office']] + [
           ['amenity', 'pub'], ['amenity', 'biergarten'], ['amenity', 'bar']] + [['amenity', 'restaurant']] + [
           ['amenity', 'telephone']] + [['amenity', 'theatre']] + [['amenity', 'toilets']] + [
           ['artwork_type', 'sculpture'], ['artwork_type', 'statue']] + [['building:architecture', 'empire'],
                                                                         ['building:architecture', 'gothic'],
                                                                         ['historic', 'building'],
                                                                         ['artwork_type', 'architecture'],
                                                                         ['building:architecture', 'neoclassicism'],
                                                                         ['building:architecture',
                                                                          'constructivism'],
                                                                         ['building:architecture', 'art_nouveau'],
                                                                         ['building:architecture', 'modern'],
                                                                         ['building:architecture', 'neo-gothic'],
                                                                         ['building:architecture', 'postmodern'],
                                                                         ['building:architecture',
                                                                          'pseudo-russian'],
                                                                         ['building:architecture',
                                                                          'russian_gothic'],
                                                                         ['building:architecture', 'contemporary'],
                                                                         ['building:architecture', 'eclectic'],
                                                                         ['historic', 'manor']] + [
           ['historic', 'battlefield'], ['historic', 'cannon'], ['historic', 'castle']] + [['historic', 'church'],
                                                                                           ['building', 'church'],
                                                                                           ['building',
                                                                                            'cathedral'],
                                                                                           ['building', 'temple'],
                                                                                           ['historic',
                                                                                            'monastery'],
                                                                                           ['building',
                                                                                            'synagogue'],
                                                                                           ['building',
                                                                                            'mosque']] + [
           ['historic', 'locomotive'], ['historic', 'aircraft'], ['historic', 'vehicle']] + [
           ['historic', 'memorial']] + [['historic', 'monument']] + [['historic', 'ruins'],
                                                                     ['historic', 'archaeological_site']] + [
           ['historic', 'ship'], ['historic', 'fort']] + [['historic', 'tomb']] + [['historic', 'tower'],
                                                                                   ['historic', 'city_gate'],
                                                                                   ['historic', 'citywalls']] + [
           ['historic', 'yes'], ['historic', 'milestone']] + [['shop', 'bakery'], ['shop', 'confectionery'],
                                                              ['shop', 'pastry']] + [['shop', 'beverages'],
                                                                                     ['shop', 'tea'],
                                                                                     ['shop', 'wine'],
                                                                                     ['shop', 'coffee'],
                                                                                     ['shop', 'water']] + [
           ['shop', 'convenience'], ['shop', 'greengrocer'], ['shop', 'butcher'], ['shop', 'deli'],
           ['amenity', 'marketplace'], ['shop', 'seafood'], ['shop', 'farm'], ['shop', 'dairy'],
           ['shop', 'health_food']] + [['tourism', 'aquarium']] + [['tourism', 'attraction'], ['tourism', 'yes'],
                                                                   ['artwork_type', 'stone'],
                                                                   ['historic', 'boundary_stone']] + [
           ['tourism', 'museum'], ['amenity', 'arts_centre'], ['tourism', 'gallery']] + [
           ['tourism', 'theme_park']] + [['tourism', 'viewpoint']] + [['tourism', 'zoo']]+[['shop', 'supermarket']]